### ISSUE TITLE
Custom logging

### ISSUE THREAD

**Issue by ThatTonybo** [danclay/eris-fleet#1]
Decent library so far but I'd like to be able to disable built-in logging so I can receive logging events on the main file (ie. `index.js`) and pipe them into my custom logging functionality.

So instead of something like this:
![image](https://user-images.githubusercontent.com/28176227/83738802-1a9da400-a698-11ea-86ff-df1e26efd635.png)
Or any sort of general logging like shard ready, it'd send a JSON object to an event (via IPC or just by using an event handler on the main Fleet) that can then be handled appropriately.

**EDIT:** Re clarifying that I'm suggesting a JSON object to be passed instead of just the errors that come right now.

**Comment by danclay** [comment]
You should be able to do whatever you want with the errors in your index.js file. It is emitted as log, debug, or error. So you could do
```js
const Admiral = new Fleet(options);

Admiral.on('log', m => {
// Do whatever you want with the log
});
Admiral.on('debug', m => {
// Do whatever you want with the log
});
Admiral.on('error', m => {
// Do whatever you want with the log
});
```

**Comment by ThatTonybo** [comment]
Got it. Side question as well ~ how do you set the shard's status? Workers don't seem to receive any ready event.

**Comment by danclay** [comment]
Each cluster is considered ready when all the shards within that cluster are ready. Your code loads after all shards within a cluster are ready.

**Comment by ThatTonybo** [comment]
So theoretically, slapping the `editStatus` code anywhere in the `bot.js` would work?

**Comment by danclay** [comment]
Yes, you shouldn't have to worry about the client not being ready in your bot.js file since it only loads the code when the client is ready.

**Comment by ThatTonybo** [comment]
Sounds good. One last question that just popped up:
Are stats not first known on start up? Tried using the `ipc.getStats()` function and it returns this:
```js
{"guilds":0,"users":0,"clustersRam":0,"voice":0,"largeGuilds":0,"shardCount":0,"clusters":[]}
```

**Comment by danclay** [comment]
Stats are started once all services and clusters have launched. It may be possible to give stats as each cluster comes online, but this will give inaccurate stats so I'm conflicted on making that change. If I give 0 for each value, then your code can know if the stats are not ready since everything is 0. You can listen for stats updates by registering the "stats" event in IPC. Here's an example:
```js
this.ipc.register("stats", (message) => {
   const stats = message.msg;
   // Do stuff with the stats
});
```

**Comment by ThatTonybo** [comment]
I'd like it to be an option. Otherwise looks good, I can just wait until the stats are ready.
