### ISSUE TITLE
Prefix missing after restarting

### ISSUE THREAD

**Issue by Tom-Beijner** [danclay/eris-fleet#11]
It seems like the prefix of the cluster is missing after restarting the clusters using the ipc, is this intended? 
![Picture of the issue](https://i.imgur.com/NYRXuwu.png)

**Comment by danclay** [comment]
That's odd. Let me check on that

**Comment by danclay** [comment]
Does it show up again after the old worker is killed?

**Comment by Tom-Beijner** [comment]
Yeah it reappears, ("Test message, is up" as reference when my bot code is running)
![Reference](https://i.imgur.com/F5FqfZZ.png)

**Comment by danclay** [comment]
Should be fixed in 0.2.3
