### ISSUE TITLE
workerID of undefined

### ISSUE THREAD

**Issue by Tom-Beijner** [danclay/eris-fleet#13]
It seems like letting the bot run I get the error of "TypeError: Cannot read property 'workerID' of undefined' occasionally appear. I don't have a consistent way of testing this other than letting the bot run.
![Reference](https://i.imgur.com/zBJlI2e.png)
_Note: The bot was running on Ubuntu_

**Comment by danclay** [comment]
Does this occur right after a cluster or service connects? Also is this v0.2.2 or v0.2.3 (so I know which line your error is referring to)

**Comment by Tom-Beijner** [comment]
Happens after Cluster connects, (I don't use a service) on v0.2.2

**Comment by danclay** [comment]
Is it after the initial connection, such as from a brief shard disconnection?

**Comment by Tom-Beijner** [comment]
Well while I was coding the bot a shard disconnected with a undefined error and after it past the ready event then it errored, (can't remember if it was right after or after some time)
![Reference](https://i.imgur.com/81xkJxo.png)

**Comment by danclay** [comment]
Should be fixed in 0.2.4
