### ISSUE TITLE
Shard disconnect error with undefined

### ISSUE THREAD

**Issue by Tom-Beijner** [danclay/eris-fleet#16]
**Describe the bug**
Shard disconnect with an error which is undefined, which later the shard resumes.

**Version**
v0.2.4

**To Reproduce**
I don't have a way to reproduce it as it seems it just happens while running.

**Expected behavior**
Show the actual error

**Screenshots**
![Reference](https://i.imgur.com/LAgKpTd.png)

**Additional context**
The issue occurred on a Ubuntu machine I have not tested if this occurs on my Windows machine.

**Comment by danclay** [comment]
This is apparently an issue with Eris and I've heard it may be fixed on the dev branch of eris.
