### ISSUE TITLE
Incorrect amount of users on clusters

### ISSUE THREAD

**Issue by Tom-Beijner** [danclay/eris-fleet#17]
**Describe the bug**
The cluster is showing 1 when the shard itself is not in a guild

**Version**
v0.2.4 

**To Reproduce**
Console log the clusters users amount

**Expected behavior**
Should display 0

**Comment by danclay** [comment]
Is this in the shard stats or cluster stats

**Comment by Tom-Beijner** [comment]
It's in the cluster stats

**Comment by danclay** [comment]
So it shows 1 user when the cluster contains 0 guilds?

**Comment by Tom-Beijner** [comment]
Yes

**Comment by danclay** [comment]
My theory is that shards in 0 guilds may still cache the bot’s user, leaving the cached user count at 1.

**Comment by danclay** [comment]
You can also create your own stats collection system using services.
